package com.jfinal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBook<M extends BaseBook<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setBookName(java.lang.String bookName) {
		set("book_name", bookName);
		return (M)this;
	}

	public java.lang.String getBookName() {
		return get("book_name");
	}

	public M setIsbn(java.lang.String isbn) {
		set("isbn", isbn);
		return (M)this;
	}

	public java.lang.String getIsbn() {
		return get("isbn");
	}

	public M setPrice(java.lang.Integer price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Integer getPrice() {
		return get("price");
	}

	public M setStock(java.lang.Integer stock) {
		set("stock", stock);
		return (M)this;
	}

	public java.lang.Integer getStock() {
		return get("stock");
	}

}
